Repository MapColonies/developer-portal, pull requests merged in 2024-10, with the labels that each got.

#93 feat(geocoding): added geocoding documentation
  docs/MapColonies/vector/Services/geocoding/README.md
  docusaurus.config.js
  static/openapi/vector/geocoding-openapi.yaml
Labels: documentation, enhancement

#104 docs: geocoding generic response object and reference to feedback API
  docs/MapColonies/vector/Services/geocoding/README.md
  static/openapi/vector/geocoding-openapi.yaml
Labels: documentation, enhancement

#100 feat: geocoding feedback api documentation
  docs/MapColonies/vector/Services/geocoding/README.md
  docs/MapColonies/vector/Services/geocoding/feedback_api.md
  docs/MapColonies/vector/Services/replication/README.md
  docusaurus.config.js
  static/openapi/vector/feedback-api-openapi.yaml
Labels: documentation

#98 docs(authentication): add explicit explanation about how to supply a token in requests
  docs/MapColonies/auth.md
Labels: documentation

#107 fix: geocoding's response examples
  docs/MapColonies/vector/Services/geocoding/README.md
Labels: documentation

#106 fix: broken links
  docs/MapColonies/3D/services/catalog/profile_v1.md
  docs/MapColonies/3D/services/catalog/profile_v2.md
  docs/MapColonies/DEM/Guides/DEM_getting_started.md
  docs/MapColonies/Raster/Guides/raster-export.mdx
  docs/MapColonies/Raster/Guides/raster-getting-started.mdx
Labels: bug

#99 feat: upgrade to docusaurus v3
  README.md
  docs/MapColonies/3D/Guides/3D_getting_started.md
  docs/MapColonies/3D/Guides/3D_terrain_min_max_height_extraction.md
  docs/MapColonies/DEM/Guides/DEM_getting_started.md
  docs/MapColonies/DEM/Services/elevation/README.md
  docs/MapColonies/Raster/Guides/raster-export.mdx
  docs/MapColonies/Raster/Guides/raster-getting-started.mdx
  docs/MapColonies/Raster/services/PolygonParts/README.md
  docs/MapColonies/Raster/services/catalog/README.md
  docs/MapColonies/Raster/services/catalog/profile_v1_0.md
  docs/MapColonies/Raster/services/export.mdx
  docs/MapColonies/Raster/services/map_service.md
  docs/MapColonies/auth.md
  docs/MapColonies/openstreetmap/nominatim/lookup.md
  docs/MapColonies/openstreetmap/nominatim/output.md
  docs/MapColonies/openstreetmap/nominatim/reverse.md
  docs/MapColonies/openstreetmap/nominatim/search.md
  docs/MapColonies/openstreetmap/osm-carto/areas.md
  docs/MapColonies/openstreetmap/valhalla/turn-by-turn/api-reference.md
  docs/MapColonies/vector/Services/geocoding/README.md
  docs/MapColonies/vector/Services/geocoding/feedback_api.md
  docs/MapColonies/vector/Services/replication/README.md
  docusaurus.config.ts
  package-lock.json
  package.json
  src/pages/index.tsx
  tsconfig.json
Labels: enhancement

#112 chore(master): release 3.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
